# Docker Compose configuration for Celery workers
# This extends the main docker-compose.yml with Celery services

version: '3.8'

services:
  # Celery Worker for KPI calculations
  celery-kpi-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info --queues=kpi_queue --concurrency=2 --hostname=kpi-worker@%h
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/goldshop
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - goldshop-network

  # Celery Worker for forecasting tasks
  celery-forecasting-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info --queues=forecasting_queue --concurrency=1 --hostname=forecasting-worker@%h
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/goldshop
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - goldshop-network

  # Celery Worker for report generation
  celery-reports-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info --queues=reports_queue --concurrency=2 --hostname=reports-worker@%h
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/goldshop
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - goldshop-network

  # Celery Beat scheduler for periodic tasks
  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app beat --loglevel=info --scheduler=celery.beat:PersistentScheduler
    volumes:
      - .:/app
      - ./celerybeat-schedule:/app/celerybeat-schedule
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/goldshop
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - goldshop-network

  # Celery Flower for monitoring (optional)
  celery-flower:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - goldshop-network

networks:
  goldshop-network:
    external: true