"""add_payment_table

Revision ID: 63fbf5b8acc6
Revises: 99d7275d4f27
Create Date: 2025-08-16 22:25:39.459672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fbf5b8acc6'
down_revision: Union[str, None] = '99d7275d4f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_customer', 'payments', ['customer_id'], unique=False)
    op.create_index('idx_payments_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_payments_invoice', 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_invoice', table_name='payments')
    op.drop_index('idx_payments_date', table_name='payments')
    op.drop_index('idx_payments_customer', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
