"""Initial migration with all core tables

Revision ID: 99d7275d4f27
Revises: 
Create Date: 2025-08-16 19:36:36.651060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d7275d4f27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_accounting_entries_reference', 'accounting_entries', ['reference_id', 'reference_type'], unique=False)
    op.create_index('idx_accounting_entries_type_date', 'accounting_entries', ['entry_type', 'transaction_date'], unique=False)
    op.alter_column('company_settings', 'invoice_template',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='invoice_template::jsonb')
    op.create_index('idx_customers_debt', 'customers', ['current_debt'], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('idx_inventory_items_active', 'inventory_items', ['is_active'], unique=False)
    op.create_index('idx_inventory_items_category', 'inventory_items', ['category_id'], unique=False)
    op.create_index('idx_inventory_items_stock', 'inventory_items', ['stock_quantity'], unique=False)
    op.create_index('idx_invoices_customer', 'invoices', ['customer_id'], unique=False)
    op.create_index('idx_invoices_date', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.alter_column('roles', 'permissions',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='permissions::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_date', table_name='invoices')
    op.drop_index('idx_invoices_customer', table_name='invoices')
    op.drop_index('idx_inventory_items_stock', table_name='inventory_items')
    op.drop_index('idx_inventory_items_category', table_name='inventory_items')
    op.drop_index('idx_inventory_items_active', table_name='inventory_items')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_debt', table_name='customers')
    op.alter_column('company_settings', 'invoice_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_accounting_entries_type_date', table_name='accounting_entries')
    op.drop_index('idx_accounting_entries_reference', table_name='accounting_entries')
    # ### end Alembic commands ###
